environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "5"

#platform:
#  - x86
#  - x64

install:
  - ps: Install-Product node $env:nodejs_version #$env:platform
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off
